site_name: TTUSSC
repo_url: https://github.com/TTUSSC/Document
copyright: Copyright &copy; 2023 TTUSSC
site_description: 大同大學科學開源服務社線上文件公開網站
nav:
  - "首頁":
    - index.md
  - "部落格":
    - blog/index.md
  - "會議記錄":
    - minutes/index.md
    - "111學年":
      - minutes/111/20230423.md
      - minutes/111/20230615.md
      - minutes/111/20230618.md
      - minutes/111/20230624.md
      - minutes/111/20230630.md
    - "112學年":
      - minutes/112/20230708.md
      - minutes/112/20230717.md
      - minutes/112/20230806.md
      - minutes/112/20230826.md
      - minutes/112/20230904.md
      - minutes/112/20230911.md
      - minutes/112/20230920.md
      - minutes/112/20231006.md
      - minutes/112/20231113.md
      - minutes/112/20240114.md
      - minutes/112/20240115.md
      - minutes/112/20240116.md
      - minutes/112/20240201.md
      - minutes/112/20240218.md
      - minutes/112/20240219.md
      - minutes/112/20240222.md
      - minutes/112/20240519.md
      - minutes/112/20240522.md
      - minutes/112/20240527.md
      - minutes/112/20240610.md
      - minutes/112/20240615.md
    - "113學年":
      - minutes/113/20240705.md
      - minutes/113/20240715.md
      - minutes/113/20240718.md
      - minutes/113/20240723.md
      - minutes/113/20240729.md
      - minutes/113/20240730.md
      - minutes/113/20240806.md
      - minutes/113/20240807_01.md
      - minutes/113/20240807_02.md
      - minutes/113/20240808.md
      - minutes/113/20240815.md
      - minutes/113/20240822.md
      - minutes/113/20240830.md
  - "社團法規":
    - laws/index.md
    - "大同大學":
      - laws/clubs_law.md
      - laws/clubs_teachers.md
      - laws/clubs_finance.md
      - laws/clubs_subsidy.md
    - "科學開源服務社":
      - laws/ssc_laws.md
      - laws/ssc_finance.md
      - laws/ssc_asset.md
    - "修定紀錄":
      - laws/commits/index.md
      - laws/commits/20230914_ssc_laws.md
  - "標籤":
    - tags.md

plugins:
  - tags:
      tags_file: tags.md
      
  - search:
      lang: zh
      separator: '[\s\u200b\-]'

  - blog:
      blog_dir: blog
      blog_toc: true
      
      post_date_format: medium
      post_url_format: "{categories}/{slug}"

      archive_toc: true
      archive: true
      archive_name: 封存

      categories_toc: true
      categories_name: 分類

      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: true
      draft_if_future_date: true
  
  # for blog posts
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

theme:
  name: material
  language: zh
  logo: assets/images/SSC_logo.png
  favicon: assets/images/favicon.ico

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.path

  # 顏色
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: 黑夜模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: 白日模式
  icon:
    #previous: fontawesome/solid/angle-left
    #next: fontawesome/solid/angle-right
    tag:
      default: material/tag
      docs: material/file
      laws: material/scale-balance
      minutes: fontawesome/solid/file-lines
      ttu: material/school
      2023camp: fontawesome/solid/campground
      arduino: simple/arduino
      ai: material/brain
      git: simple/git
      linux: fontawesome/brands/linux
      c: material/language-c
      cpp: material/language-cpp
      python: material/language-python
      md: material/language-markdown
      membertrain: material/google-classroom

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 中文
      link: /zh-TW/
      lang: zh-TW

  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ttussc_
      name: Instagram
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dEPdDmSr
      name: Discord
      
  tags:
    "文件": docs
    "模板": template
    "Arduino": arduino
    "人工智慧": ai
    "會議記錄": minutes
    "法規": laws
    "2023 科學探索家": 2023camp
    "大同大學": ttu
    "Git": git
    "Linux": linux
    "C語言": c
    "C++": cpp
    "Python": python
    "Markdown": md
    "幹部訓練": membertrain


# markdown 渲染選項
markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # Buttons
  - attr_list

  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  # Data Tables
  - tables

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Footnotes
  - footnotes

  #Formating
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Icon, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Images
  - attr_list
  - md_in_html

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - toc
  - extra
  - sane_lists
  - meta
  - pymdownx.details
  - pymdownx.superfences