site_name: TTUSSC Docs
theme:
  name: material
  language: zh-TW
  logo: assets/SSC_logo.png
  favicon: images/favicon.png


  # 顏色
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 中文
      link: /zh-TW/
      lang: zh-TW

