authors:
  tpg:
    name: "曹莛宥"        # Author name
    description: "" # Author description
    avatar: https://bulma.io/images/placeholders/96x96.png # Author avatar

  rj:
    name: "林靖疆"        # Author name
    description: "" # Author description
    avatar: https://bulma.io/images/placeholders/96x96.png # Author avatar